apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::361328292194:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::361328292194:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GWDLQIBVJFJL
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-03T06:23:29Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-04-03T06:23:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1438"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5f3127dc-858e-4cfe-8359-5eb548f65c72
